### ISSUE TITLE
"Root" explorer does not work @internal, but on SD card

### ISSUE THREAD

**Issue by ghost** [jawa0919/adb-helper#1]
My Samsung M21 with Android 11 is not rooted.

The SD card explorer works.

The root / internal explorer shows only:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/88657610/130333540-b3984b9a-ec03-4cf1-9e6b-b15d0c94d264.png">

(the encrypted SD:)

<img width="522" alt="image" src="https://user-images.githubusercontent.com/88657610/130333570-fc1d0d58-d6d9-4883-9e6a-7dbc3e8dc3d7.png">

THX

**Comment by jawa0919** [comment]
maybe Android11 that RootExplorer has some storage privileges.

 The ADB command log is displayed in the OUTPUT window. You can try to execute it on the terminal. pasting it here.

**Comment by ghost** [comment]
First, it's empty.

<img width="932" alt="image" src="https://user-images.githubusercontent.com/88657610/130521260-bf52bce6-8ca5-4078-9d72-70f740997c1c.png">

Can you give me an exact _todo_ for this?

**Comment by jawa0919** [comment]
> First, it's empty.
> 
> <img alt="image" width="932" src="https://user-images.githubusercontent.com/88657610/130521260-bf52bce6-8ca5-4078-9d72-70f740997c1c.png">
> 
> Can you give me an exact _todo_ for this?

display language English 

![20210824091814](https://user-images.githubusercontent.com/18129670/130540375-895dd9d0-3cac-41b6-a860-692f4069b8c0.png)

**Comment by jawa0919** [comment]
我需要一些日志

I need some logs
