### ISSUE TITLE
Adb logcat feature

### ISSUE THREAD

**Issue by Onekki** [jawa0919/adb-helper#11]
Hello, are you interested in adding the function of adb logcat?

**Comment by jawa0919** [comment]
Sorry, I didn't plan to develop this feature . If you are a professional Android developer, you should use Android Studio software.

The original intention of this project is to develop flutter with vscode.

I went to investigate, this function is more complicated, I don't have time

If you are interested, you can submit relevant PR

---original---

sorry，没有打算开发这个功能，如果是专业的Android开发者应该用Android Studio软件。

做这个项目的初衷是给用vscode开发flutter使用的。

我去调研了下，这个功能比较复杂，没有时间开发这个。

如果有兴趣可以提交相关PR

**Comment by jawa0919** [comment]
try
