### ISSUE TITLE
Not work on linux

### ISSUE THREAD

**Issue by sr-tream** [jawa0919/adb-helper#12]
v0.3.3 - work properly
v0.4.0 - can't find device
v0.4.1 and newer - do not show in sidebar

**Comment by jawa0919** [comment]
try to open Command Panel and  input  "Start/Restart Adb"

**Comment by sr-tream** [comment]
![image](https://user-images.githubusercontent.com/12231048/208330753-95ec65aa-6910-4c1e-bd12-67efcb00a56e.png)

**Comment by jawa0919** [comment]
you use old version . try instell  latest version 0.4.5

https://marketplace.visualstudio.com/items?itemName=jawa0919.adb-helper

> ![image](https://user-images.githubusercontent.com/12231048/208330753-95ec65aa-6910-4c1e-bd12-67efcb00a56e.png)

**Comment by jawa0919** [comment]
when project have “AndroidManifest.xml” /”*.apk“/”.metadata“ file , plugin auto start,show in sidebar

if not have, must  command "Start/Restart Adb" start

Feature start in v0.4.0

**Comment by sr-tream** [comment]
![image](https://user-images.githubusercontent.com/12231048/208419451-1475a348-7a3d-4668-8890-be7c1c63f591.png)

**Comment by sr-tream** [comment]
AndroidManifest.xml is present in app/src/main, but plugin won't start

**Comment by sr-tream** [comment]
It's also show notify
![image](https://user-images.githubusercontent.com/12231048/208420216-b21fe776-5bfa-43f2-8426-41ef67d362d2.png)

but paths is set
![image](https://user-images.githubusercontent.com/12231048/208420263-f4d31675-6adf-4305-a652-2ef6d38710e9.png)

```bash
file /usr/bin/adb
/usr/bin/adb: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=f047e8c5e273373c906b2cd48dd94f7f818326fd, for GNU/Linux 4.4.0, stripped
```

**Comment by jawa0919** [comment]
`/usr/bin/adb` => `/usr/bin`

`/usr/bin/scrcpy` => `/usr/bin`

try

**Comment by jawa0919** [comment]
Generally, if you can run the `adb` and `scrcpy` commands on the terminal, you do not need to set path

I don't have a Linux device, so I don't know whether this code can run normally

https://github.com/jawa0919/adb-helper/blob/9e821484dbb265bbe2b700f3306d359471e2c6cb/src/core/app/AppConfig.ts#L35-L52

**Comment by sr-tream** [comment]
> `/usr/bin/adb` => `/usr/bin`
> 
> `/usr/bin/scrcpy` => `/usr/bin`

This not work, so with `/` at end it also not work.


> Generally, if you can run the `adb` and `scrcpy` commands on the terminal, you do not need to set path

With empty fields also not work

`ANDROID_HOME` and `ANDROID_SDK_ROOT` is set to `/opt/android-sdk`. `PATH` contains `/usr/bin` with `adb` executable


> sdkPaths = sdkPaths.map((p) => (basename(p) === "platform-tools" ? p : join(p, "platform-tools")));

I don't know TS. This code always searches adb executable in `platform-tools`? Then - it's reason of my issue. My adb executable not in `platform-tools`

**Comment by jawa0919** [comment]
In Android development, `adb` is usually in`%ANDROID_SDK_ROOT%/platform tools`

**Comment by sr-tream** [comment]
> In Android development, `adb` is usually in`%ANDROID_SDK_ROOT%/platform tools`

Thanks. Its work with symlink of adb to `/opt/android-sdk/platform-tools`

**Comment by jawa0919** [comment]
fix  if `adb` not in android sdk path adbBinPath error ,pls instell new version.  add some tip in setting /readme
