### ISSUE TITLE
how open files 

### ISSUE THREAD

**Issue by fahmyabada** [jawa0919/adb-helper#13]
![333](https://github.com/jawa0919/adb-helper/assets/53784773/18fbe3a3-d97e-4062-b496-0738ca90a31f)

when click on flutterSharedPreference.xml 

show 
![eee](https://github.com/jawa0919/adb-helper/assets/53784773/5e57356f-208e-4ed1-b926-55fdb9f107d5)

and i try to save as in folder show success saved but when go folder not found any thing

**Comment by jawa0919** [comment]
this path have some permission denied

**Comment by jawa0919** [comment]
This permission issue will be resolved no later than next month.

**Comment by jawa0919** [comment]
update and try

**Comment by fahmyabada** [comment]
now name package doesn't appear anymore, despite it used to appear before.
i can't see files to open

**Comment by jawa0919** [comment]
chooseRootPath maybe help you
![QQ截图20230807100527](https://github.com/jawa0919/adb-helper/assets/18129670/5426a7b6-b420-4a52-89b4-3af82496e73a)
![QQ截图20230807100538](https://github.com/jawa0919/adb-helper/assets/18129670/15f8158a-527b-48a5-a0f7-ed2db4e1cce8)
