### ISSUE TITLE
ls: /data/: Permission denied

### ISSUE THREAD

**Issue by only52607** [jawa0919/adb-helper#14]
我的设备有root权限，但用根目录打开文件管理器，会提示/data目录无权限访问。

控制台输出的命令为 
`adb -s xxxx shell ls /data/ -l`
我复制下来，手动运行会出现
`ls: /data/: Permission denied`

但改为
`adb -s xxxx shell su -c ls /data/ -l`
则正常

能否提供一个选项，让adb执行shell命令的时候自动加上前缀`su -c` ？

**Comment by jawa0919** [comment]
可以加，但最近没时间

**Comment by jawa0919** [comment]
我手上没有root设备，没办法对照开发。
权限问题很难完美处理。
尝试用run-as的方式绕过一些文件权限，但效果一般。
所以我就没有深入开发的想法。
在v0.6.1上线了打开设备shell的功能，也许帮助你

I don't have a root device on hand, so I can't compare it with development.
Permission issues are difficult to handle perfectly.
Attempted to bypass some file permissions using run as, but the effect was average.
So I don't have the idea of delving deeper into development.
The ability to open device shells has been launched in v0.6.1, which may help you

![openShell](https://raw.githubusercontent.com/jawa0919/adb-helper/7eaa33e08dfd6a9a2c848bee7ac37a5baf821031/docs/img/openShell.png)
