### ISSUE TITLE
Suggestion: Enable Extension in Sidebar without need to open Android Project

### ISSUE THREAD

**Issue by androidotai** [jawa0919/adb-helper#15]
I notice to make this extension appear in sidebar, we need to be in Android Project. But sometimes, I want to access this extension without any Android Project. How to enable it?

**Comment by jawa0919** [comment]
[ "onCommand:adb-helper.restartAdb"](https://github.com/jawa0919/adb-helper/blob/c624d9eedf3e55e8026f7a569f543545005115d6/package.json#L39)
