### ISSUE TITLE
Feature Request - Directly launch adb shell session for a connected device

### ISSUE THREAD

**Issue by tfuerholzer** [jawa0919/adb-helper#17]
Simply put, it would be really useful for me if I could directly select a device and connect to it with the adb shell command and open a shell session that way. If you (the maintainer) are open to the idea I could look into adding that feature in a PR.

Kind regards

**Comment by jawa0919** [comment]
good idea

Welcome to submit PR

**Comment by jawa0919** [comment]
v0.6.1 support  open shell

![openShell](https://raw.githubusercontent.com/jawa0919/adb-helper/7eaa33e08dfd6a9a2c848bee7ac37a5baf821031/docs/img/openShell.png)
