### ISSUE TITLE
Features: open by double-clicking and copy

### ISSUE THREAD

**Issue by ghost** [jawa0919/adb-helper#2]
I want to open those files by double-clicking in a tab / external - however

<img width="522" alt="image" src="https://user-images.githubusercontent.com/88657610/130333625-a6b8f902-fbba-4df0-9a02-17db3f19fb4f.png">

with that I am able to view and / or save the file,

but I would like to get a "copy" by secondary click, too, to paste it into my tree.

THX

**Comment by jawa0919** [comment]
I'm developing this feature.

To open / copy a file, I need to implement a file provider in vscode,

**Comment by jawa0919** [comment]
> I want to open those files by double-clicking in a tab / external - however
> 
> <img alt="image" width="522" src="https://user-images.githubusercontent.com/88657610/130333625-a6b8f902-fbba-4df0-9a02-17db3f19fb4f.png">
> 
> with that I am able to view and / or save the file,
> 
> but I would like to get a "copy" by secondary click, too, to paste it into my tree.
> 
> THX

In the new version, the function of viewing some equipment files is added

**Comment by jawa0919** [comment]
I will close this issue
