### ISSUE TITLE
Feature: adb connect IP

### ISSUE THREAD

**Issue by ghost** [jawa0919/adb-helper#3]
Right now it seems only to be an extension for file / app viewing?

I would like to use it for `add connect IP` by simply clicking a recent history and please a favorite on which is simply a click far away (I really dislike I do not have a button to connect to my favorite phone generally).

THX

**Comment by jawa0919** [comment]
Are you talking about connecting to the mobile phone through WiFi? 

The device item has a broadcast icon

**Comment by ghost** [comment]
I am talking about __wireless-adb__ and want to start it by this extension instead of typing it into the terminal or using another adb-extension.

This extension seems to work only with _new_ connections. It should remember recent and in generally have an option to start wireless-adb on the fly.

**Comment by jawa0919** [comment]
> I am talking about **wireless-adb** and want to start it by this extension instead of typing it into the terminal or using another adb-extension.
> 
> This extension seems to work only with _new_ connections. It should remember recent and in generally have an option to start wireless-adb on the fly.

In new version, you can  edit command. and use command history in expanded tree. Maybe it can help you

see

![Home](https://raw.githubusercontent.com/jawa0919/adb-helper/main/docs/assets/command.png)
