### ISSUE TITLE
不兼容linux版 vs code？

### ISSUE THREAD

**Issue by qiurigao** [jawa0919/adb-helper#4]
![截图_2021-09-02_16-22-51](https://user-images.githubusercontent.com/22121479/131809281-8f861b09-e8c1-4f19-b39b-7f27e2d212cd.png)

**Comment by jawa0919** [comment]
vscode版本低了，最低是1.59
https://github.com/jawa0919/adb-helper/blob/e7c5189e991c7dc1b92a8eb011f908691e328ee8/package.json#L20-L22

**Comment by jawa0919** [comment]
插件对vscode版本没什么要求，新的版本0.1.0版本中我降级到1.57.0
