### ISSUE TITLE
permissions for user folder

### ISSUE THREAD

**Issue by gkrawiec** [jawa0919/adb-helper#7]
Hi, finally a file explorer GUI. Thanks!
I have a question, I am trying to reach this folder

`/data/user/0/com.example.myApp/app_flutter/myApptext.txt
`
How do I get there? I don't see the `user` folder. I am guessing it's a permissions issue, so how would I give it permissions to see that folder in the emulator?
thank you.

**Comment by jawa0919** [comment]
The new version fixes the problem that some files cannot be viewed due to lack of permission

**Comment by jawa0919** [comment]
I will close this issue
