### ISSUE TITLE
[feature] adb pair

### ISSUE THREAD

**Issue by gpibarra** [jawa0919/adb-helper#8]
In addition to the possibility of connecting with ip, a device can be paired from the qr code as android studio does ([https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi-android-11+](https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi-android-11+))
Example [https://github.com/aakash-pamnani/ADB-QR](https://github.com/aakash-pamnani/ADB-QR)

**Comment by jawa0919** [comment]
v0.4.2 support pair
![QQ截图20220521194147](https://user-images.githubusercontent.com/18129670/169650151-0ea173d8-8dba-4977-a1b4-44de51a76f43.png)
